# Generated by Django 2.2.13 on 2020-07-22 03:22

import arfrontconfig.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AricleContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('honor', 'honor'), ('tos', 'tos'), ('privacy', 'privacy')], default='privacy', max_length=32, unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'aritlecontent',
                'verbose_name': 'aricle content',
                'verbose_name_plural': 'aricle content',
            },
        ),
        migrations.CreateModel(
            name='Lmsbannerlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banner', models.ImageField(default='', upload_to=arfrontconfig.models.user_directory_path, verbose_name='banner path')),
                ('order_id', models.IntegerField(default=1, verbose_name='Sort')),
            ],
            options={
                'db_table': 'lmsbannerlist',
                'verbose_name': 'Lms banner',
                'verbose_name_plural': 'Lms banner',
            },
        ),
        migrations.CreateModel(
            name='NewerguideRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('live_guide', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'newerguiderecord',
            },
        ),
        migrations.CreateModel(
            name='Youtubeaccountconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('username', models.TextField(blank=True, verbose_name='User')),
                ('password', models.TextField(blank=True, verbose_name='Password')),
                ('streamersite', models.TextField(blank=True, verbose_name='Streamer Site')),
                ('target_url', models.TextField(blank=True, verbose_name='Target url')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'db_table': 'youtubeaccountconfig',
                'verbose_name': 'Youtube account(h5 page)',
                'verbose_name_plural': 'Youtube account(h5 page)',
            },
        ),
        migrations.CreateModel(
            name='WeihouaccountConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('username', models.TextField(blank=True, verbose_name='User')),
                ('password', models.TextField(blank=True, verbose_name='Password')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'db_table': 'weihouaccountconfig',
                'verbose_name': 'Weihou account',
                'verbose_name_plural': 'Weihou account',
            },
        ),
        migrations.CreateModel(
            name='AlipayinfoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('appid', models.TextField(blank=True, verbose_name='appid')),
                ('app_private_key', models.TextField(blank=True, verbose_name='app_private_key')),
                ('alipay_public_key', models.TextField(blank=True, verbose_name='alipay_public_key')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'db_table': 'alipayinfoconfig',
                'verbose_name': 'Alipay info',
                'verbose_name_plural': 'Alipay info',
            },
        ),
    ]
