# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-12 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arfrontconfig', '0002_auto_20191210_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeaccountconfig',
            name='target_url',
            field=models.TextField(blank=True, verbose_name='Target url'),
        ),
    ]
