# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-20 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arfrontconfig', '0003_youtubeaccountconfig_target_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeihouaccountConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('username', models.TextField(blank=True, verbose_name='User')),
                ('password', models.TextField(blank=True, verbose_name='Password')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'db_table': 'weihouaccountconfig',
                'verbose_name': 'Weihou account',
                'verbose_name_plural': 'Weihou account',
            },
        ),
    ]
