# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-01 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arfrontconfig', '0004_weihouaccountconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewerguideRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('live_guide', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'newerguiderecord',
            },
        ),
    ]
