# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-14 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arfrontconfig', '0005_newerguiderecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayinfoConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('appid', models.TextField(blank=True, verbose_name='appid')),
                ('app_private_key', models.TextField(blank=True, verbose_name='app_private_key')),
                ('alipay_public_key', models.TextField(blank=True, verbose_name='alipay_public_key')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'db_table': 'alipayinfoconfig',
                'verbose_name': 'Alipay info',
                'verbose_name_plural': 'Alipay info',
            },
        ),
    ]
