# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-20 09:16
from __future__ import unicode_literals

import arfrontconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arfrontconfig', '0006_alipayinfoconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lmsbannerlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banner', models.ImageField(default='', upload_to=arfrontconfig.models.user_directory_path, verbose_name='banner path')),
                ('order_id', models.IntegerField(default=1, verbose_name='Sort')),
            ],
            options={
                'db_table': 'lmsbannerlist',
                'verbose_name': 'Lms banner',
                'verbose_name_plural': 'Lms banner',
            },
        ),
    ]
