# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-29 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arfrontconfig', '0007_lmsbannerlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AricleContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('honor', 'honor'), ('tos', 'tos'), ('privacy', 'privacy')], default='privacy', max_length=32, unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'aritlecontent',
                'verbose_name': 'aricle content',
                'verbose_name_plural': 'aricle content',
            },
        ),
    ]
