# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-20 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arfrontconfig', '0008_ariclecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordVerifyCodeDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phonenum', models.CharField(blank=True, default='', max_length=128)),
                ('code', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.IntegerField(default=1, verbose_name='\u9a8c\u8bc1\u5417\u662f\u5426\u6709\u6548')),
                ('send_type', models.CharField(default='', max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recordverifycodedetail',
                'verbose_name': 'record verify code detail',
                'verbose_name_plural': 'record verify code detail',
            },
        ),
    ]
