# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-22 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arfrontconfig', '0009_recordverifycodedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsDetailConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Change date')),
                ('enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('account', models.CharField(default='', max_length=128, verbose_name='Account')),
                ('pwd', models.CharField(default='', max_length=128, verbose_name='Pwd')),
                ('content', models.CharField(default='', max_length=256, verbose_name='Content')),
                ('templateid', models.CharField(default='', max_length=128, verbose_name='TemplateId')),
                ('signid', models.CharField(default='', max_length=128, verbose_name='SignId')),
                ('changed_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
            ],
            options={
                'db_table': 'smsdetailconfig',
                'verbose_name': 'Sms detail',
                'verbose_name_plural': 'Sms detail',
            },
        ),
    ]
