# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-28 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoverview',
            name='course_image_url',
            field=models.TextField(default=b'/static/images/default_course_image.jpg'),
        ),
    ]
