# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-07 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0004_change_meta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='out_trade_no',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
