# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0005_order_out_trade_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
