# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-13 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0006_order_order_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[(b'alipay', b'alipay'), (b'wechatpay', b'wechatpay')], default=b'alipay', max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default=b'cny', max_length=8),
        ),
    ]
