# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-04-13 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0007_auto_20200413_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pay_method',
            new_name='pay_type',
        ),
    ]
