# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-09 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0008_auto_20200413_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='out_trade_no',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
