# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-06 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingtalkuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dingtalkuserconfig',
            name='secret',
            field=models.TextField(blank=True, verbose_name='Client Secret'),
        ),
    ]
