# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-02-13 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dingtalkuser', '0002_auto_20191106_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='dingtalkuserconfig',
            name='corpId',
            field=models.TextField(blank=True, verbose_name='corpId'),
        ),
    ]
