# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-05-21 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20181221_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phonenum',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
